### ISSUE TITLE
miss file redis.ddl  for redis connector

### ISSUE THREAD

**Issue by axingblog** [voxpupuli/puppet-mcollective#245]
``` 
Starting daemon:  mcollective
/usr/lib/ruby/vendor_ruby/mcollective/ddl/base.rb:83:in `loadddlfile': Can't find DDL for connector plugin 'redis' (RuntimeError)
	from /usr/lib/ruby/vendor_ruby/mcollective/ddl/base.rb:31:in `initialize'
	from /usr/lib/ruby/vendor_ruby/mcollective/ddl.rb:85:in `new'
	from /usr/lib/ruby/vendor_ruby/mcollective/ddl.rb:85:in `rescue in load_and_cache'
	from /usr/lib/ruby/vendor_ruby/mcollective/ddl.rb:76:in `load_and_cache'
	from /usr/lib/ruby/vendor_ruby/mcollective/ddl.rb:66:in `new'
	from /usr/lib/ruby/vendor_ruby/mcollective/connector/base.rb:21:in `inherited'
	from /usr/local/share/mcollective/mcollective/connector/redis.rb:23:in `<module:Connector>'
	from /usr/local/share/mcollective/mcollective/connector/redis.rb:5:in `<module:MCollective>'
	from /usr/local/share/mcollective/mcollective/connector/redis.rb:4:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/mcollective/pluginmanager.rb:169:in `load'
	from /usr/lib/ruby/vendor_ruby/mcollective/pluginmanager.rb:169:in `loadclass'
	from /usr/lib/ruby/vendor_ruby/mcollective/config.rb:161:in `loadconfig'
	from /usr/sbin/mcollectived:57:in `<main>'
```

**Comment by jyaworski** [comment]
Hello:

Is this still an issue?

**Comment by jyaworski** [comment]
Closing due to lack of response. Please re-open if this is still an issue.
