### ISSUE TITLE
I don't think this works on Ubuntu 12.04.

### ISSUE THREAD

**Issue by kwolf** [voxpupuli/puppet-mcollective#302]

**Comment by bastelfreak** [comment]
hi,
Why do you think this doesn't work? have you tested it and could provide any error messages?

**Comment by kwolf** [comment]
I  hit enter and posted a blank body.  It's been updated.  My bad.

**Comment by luksi1** [comment]
I can second this. The MCollective server, client will not work on Ubuntu 12.04 with SSL activated. 

`E, [2016-09-27T13:28:42.487939 #26654] ERROR -- : activemq.rb:377:in `ssl_parameters' Failed to set full SSL verified mode: RuntimeError: Stomp gem >= 1.2.2 is needed
E, [2016-09-27T13:28:42.488112 #26654] ERROR -- : runner.rb:107:in `main_loop' A failure occurred in the MCollective runner.
E, [2016-09-27T13:28:42.488282 #26654] ERROR -- : runner.rb:108:in `main_loop' Could not connect to ActiveMQ Server: Stomp gem >= 1.2.2 is needed
E, [2016-09-27T13:28:42.488358 #26654] ERROR -- : runner.rb:109:in `main_loop' /usr/lib/ruby/vendor_ruby/mcollective/connector/activemq.rb:301:in `connect'
        /usr/lib/ruby/vendor_ruby/mcollective/runner.rb:164:in `receiver_thread'
        /usr/lib/ruby/vendor_ruby/mcollective/runner.rb:142:in `start_receiver_thread'
        /usr/lib/ruby/vendor_ruby/mcollective/runner.rb:140:in `initialize'
        /usr/lib/ruby/vendor_ruby/mcollective/runner.rb:140:in `new'
        /usr/lib/ruby/vendor_ruby/mcollective/runner.rb:140:in `start_receiver_thread'
        /usr/lib/ruby/vendor_ruby/mcollective/runner.rb:71:in `main_loop'
        /usr/lib/ruby/vendor_ruby/mcollective/unix_daemon.rb:60:in `daemonize_runner'
        /usr/lib/ruby/vendor_ruby/mcollective/unix_daemon.rb:13:in `daemonize'
        /usr/lib/ruby/vendor_ruby/mcollective/unix_daemon.rb:5:in `fork'
        /usr/lib/ruby/vendor_ruby/mcollective/unix_daemon.rb:5:in `daemonize'
        /usr/lib/ruby/vendor_ruby/mcollective/unix_daemon.rb:20:in `daemonize_runner'
        /usr/sbin/mcollectived:74
`

You'll need to upgrade ruby-stomp to get this to work. What about a check on the ruby-stomp version if SSL is enabled?

**Comment by antaflos** [comment]
The ruby-stomp problem has been around for a while. I remember opening issue https://tickets.puppetlabs.com/browse/MODULES-459 and sending PR https://github.com/voxpupuli/puppet-mcollective/pull/121 to allow specifying the ruby-stomp version. We usually set it to "latest".
